Test Quarantine (#38)
* Add skip testing functionality

* Add e2e test for skip_testing input and a sample workflow

* Fix yaml lint issues and update README

* Test quarantine

* Update README

* Rename test_quarantined_tests e2e test

* Code cleanup

* Code cleanup

* Merge test_gradle-kts and test_quarantined_tests e2e tests

* Update quarantined tests parsing

* Use https://github.com/bitrise-samples/android-gradle-kotlin-dsl from master branch

* Update go-steputils

* Move init script template to a constant

* Introduce runStep function and improve logging

* Update Quarantined tests input

* Explicitly specify init script for the testing Gradle command

diff --git a/e2e/bitrise.yml b/e2e/bitrise.yml
--- a/e2e/bitrise.yml
+++ b/e2e/bitrise.yml
@@ -46,17 +46,41 @@ workflows:
     steps:
     - bundle::setup-test-app:
         inputs:
-        - sample_app_url: https://github.com/bitrise-samples/android-gradle-kotlin-dsl
+        - sample_app_url: https://github.com/bitrise-samples/android-gradle-kotlin-dsl.git
         - sample_app_branch: master
     - path::./:
         inputs:
         - module: app
-        - variant: Release
-        - is_debug: "true"
+        - variant: debug
+        - quarantined_tests: |-
+            [
+              {
+                "testCaseName": "addition_isCorrect",
+                "testSuiteName": [
+                  "app-debug"
+                ],
+                "className": "org.gradle.kotlin.dsl.samples.androidstudio.ExampleUnitTest"
+              }
+            ]
     - bundle::check-artifacts:
         inputs:
         - module: app
-        - variant: Release
+        - variant: Debug
+    - script:
+        title: Check if skipped tests are really skipped
+        inputs:
+        - content: |
+            test_results_xml_path="./app/build/test-results/testDebugUnitTest/TEST-org.gradle.kotlin.dsl.samples.androidstudio.ExampleUnitTest.xml"
+            if [ ! -f "$test_results_xml_path" ]; then
+              echo "No test results xml found at: $test_results_xml_path"
+              exit 1
+            fi
+            if grep -q '<testcase name="addition_isCorrect"' "$test_results_xml_path"; then
+              echo "The skipped test was found in the test results xml."
+              exit 1
+            else
+              echo "The skipped test was NOT found in the test results xml."
+            fi
 
 step_bundles:
   setup-test-app:
